# Generated by Django 4.2.3 on 2023-10-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datasets',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('dataset_path', models.TextField()),
                ('language', models.CharField(max_length=20)),
                ('task_name', models.CharField(max_length=50)),
                ('set_name', models.CharField(max_length=20)),
                ('user_email', models.CharField(max_length=50)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
